Jnci ruby edits 10182018
optimizely-christine/ruby_full_stack_demo pull request #1
Opened 2018-10-18 14:41 UTC by jamesneimanconsulting

@optimizely-christine Kindly review these changes and merge if approved. Please ask Mike Ng to review.
Please see https://optimizely.atlassian.net/projects/EDU/issues/EDU-2372 for more information.

2018-12-03 18:52 UTC, aliabbasrizvi requested changes
The other demo app descriptions talk a lot about set up. This one does not go into details about set up on Optimizely. Thoughts @jamesneimanconsulting ?

2018-12-03 18:52 UTC, aliabbasrizvi commented on README.md
> +* Github account configured with [SSH keys](https://help.github.com/articles/connecting-to-github-with-ssh/)
nit. GitHub.

2018-12-03 18:52 UTC, aliabbasrizvi commented on README.md
> +- You can update the Optimizely variation code in the [bin/app.rb](bin/app.rb) file.
May be show where variation code lives by mentioning code block here.

2018-12-03 18:53 UTC, aliabbasrizvi requested changes
Setting to revise so that you can take a look.

2018-12-12 16:30 UTC, jamesneimanconsulting commented
@aliabbasrizvi I have pushed another commit to this PR. Kindly let me know if there are other changes required.

2022-04-22 23:38 UTC, closed without merging